### ISSUE TITLE
mint-y-icons: mypaint and pinta have the same icon

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint-19.1-beta#17]
**Describe the bug**
Two Graphics Programs (MyPaint and Pinta) Show the Same Mint-Y Icon.

**To Reproduce**
1. Install mypaint and pinta 
2. Check to see Mint-Y Icon theme is selected
3. Go to Start Menu | Graphics 
4. See that both graphics programs have the same icon
5. Switch to Mint-X Icon theme and check again and see that they are different.

**Expected behavior**
Expected icons to be different in Mint-Y theme as they are in the Mint-X theme.

**Frequency**
Does the issue happen:
[x] Always
[ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
[x] Cinnamon Edition
[ ] MATE Edition
[ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
[x] Post-install
[x] Live session

Screenshots

Locale:
LANG=en_US.UTF-8
LANGUAGE=en_US

Drivers:
N/A

Additional context
N/A

**Comment by NikoKrause** [comment]
Hey,

yes, there are indeed some applications as `mypaint` and `pinta` in Mint-Y, which use the same icon.
They both use a generic icon called `accessories-painting`.

Creating icons is a very time consuming activity. Mint-Y uses a unique (roundish) shape for it's application icons, which are inherited from the Moka icon theme by snwh, who did a great job.
The pro of this unique shape is that you have consistent icons. The con is that you have to create for each available app its own icon (at least in theory). But that's a neverending herculean task, because:
* there are a lot of applications available in the app store
* there are releases of new applications
* some applications decide to change the names of their icons
* flatpak has it's own naming rules for icons
* ....
Just to get an idea of the size of this taks, have a look at icon requests in the Moka icon theme repo (which is a 1 man (snwh) repo): https://github.com/snwh/moka-icon-theme/issues?page=1&q=is%3Aissue+is%3Aopen
(100 open requests for more than 100 icons, 243 requests closed)

So you'll either end up with the default icons, which are shipped by its application and don't fit into the Mint-Y theme because they have a different shape, or you'll end up using some generic/duplicate icons for applications.

For instance Mint-Y currently uses the `accessories-painting` icon for the following applications:
* gnome-paint
* gpaint
* kolourpaint
* mtpaint
* mypaint
* pinta
* tuxpaint

That said, it doesn't mean, that we don't want to change the icon. On the contrary we would like to have different icons and we are thankful for any contribution/pull request.
But as far as I know, right now nobody works on creating new icons for pinta, etc. and therefore it's unlikely to change in Mint 19.1.

I hope this does explain a little bit, why there are duplicate icons for `pinta` and `mypaint`.

**Comment by Acheron17** [comment]
I run the following after applications are installed to work around this:

echo "Correct a few Mint-Y-Icons for Mint 19 until fix is released ..."
sleep 1
sudo sed -i 's+Icon=bluegriffon+Icon=/usr/share/icons/Mint-X/apps/96/bluegriffon.svg+' /usr/share/applications/bluegriffon.desktop
sudo sed -i 's+Icon=mypaint+Icon=/usr/share/icons/Mint-X/apps/96/mypaint.svg+' /usr/share/applications/mypaint.desktop
sudo sed -i 's+Icon=kpat+Icon=/usr/share/icons/hicolor/64x64/apps/kpat.png+' /usr/share/applications/org.kde.kpat.desktop
sudo sed -i 's+Icon=pinta+Icon=/usr/share/icons/Mint-X/apps/96/pinta.svg+' /usr/share/applications/pinta.desktop
sudo sed -i 's+Icon=gnome-aisleriot+Icon=/usr/share/icons/Mint-X/apps/96/gnome-aisleriot.svg+' /usr/share/applications/sol.desktop

I was just hoping we could get it fixed for everyone else.  Thank you for taking the time for the detailed explanation.

**Comment by Acheron17** [comment]
If I could get you a set of icons (which i just finished) could you review them for inclusion? @NikoKrause

**Comment by clefebvre** [comment]
@Harry-W-Haines-III yes, you can create a PR on github.com/linuxmint/mint-y-icons

**Comment by NikoKrause** [comment]
We have a `src` directory with SVG files, from which the PNG files are created: https://github.com/linuxmint/mint-y-icons/blob/master/src/apps/accessories-painting.svg

**Comment by Acheron17** [comment]
So I would need to edit that file by hand instead of with Inkscape?  I edited the SVG file here on the computer but I can't upload it here.

**Comment by NikoKrause** [comment]
You can edit the svg file with Inkscape

**Comment by Acheron17** [comment]
The three SVG files are ready.

**Comment by Acheron17** [comment]
Its not immediately clear to me how to get the XML file from Inkscape.

**Comment by Acheron17** [comment]
I think I got it now ...
