### ISSUE TITLE
Mint-y-Darker dark font on dark menu in Franz

### ISSUE THREAD

**Issue by otavioschwanck** [linuxmint/mint-19.1-beta#26]
**Describe the bug**

**To Reproduce**
1. Set theme to Mint-y-Darker
2. Open franz

**Expected behavior**
White text on menu

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [ ] Live session

**Screenshots**

**Locale:**
Paste the output of `locale`.
pt-BR

**Drivers:**
Paste the output of `inxi -Gxx`.
amdgpu

**Crash report:**

Screenshot:
![image](https://user-images.githubusercontent.com/9551316/49678077-4b802700-fa69-11e8-8e47-0452df4e0271.png)

**Comment by MegaV0lt** [comment]
I have the same behavior in Mint Cinnamon 18.3

**Comment by smurphos** [comment]
Plenty of other themes have this issue with Franz and other applications built using Electron. It's not a bug with Mint-Y-Darker. I'd report it here https://github.com/meetfranz/franz/issues and reference https://github.com/electron/electron/pull/14785

**Comment by otavioschwanck** [comment]
But, Mint-Y Dark works well...

**Comment by smurphos** [comment]
The bug in Electron/Franz is that it is not using the right  background / foreground  colors for the menubar and is mixing menubar and menu colors. If your theme uses the same or similar colours for both it's not an apparent problem i.e. in Mint-Y-Dark. If your theme uses very different colors for both then it becomes a problem i.e Mint-Y-Darker.

The bug looks to have recently been fixed in Electron... https://github.com/electron/electron/pull/15878 ... so hopefully it won't be long until a new Franz version comes out with the fix.

**Comment by otavioschwanck** [comment]
> The bug in Electron/Franz is that it is not using the right background / foreground colors for the menubar and is mixing menubar and menu colors. If your theme uses the same or similar colours for both it's not an apparent problem i.e. in Mint-Y-Dark. If your theme uses very different colors for both then it becomes a problem i.e Mint-Y-Darker.
> 
> The bug looks to have recently been fixed in Electron... [electron/electron#15878](https://github.com/electron/electron/pull/15878) ... so hopefully it won't be long until a new Franz version comes out with the fix.

I understand, thank you very much for the explanation.  Closing the issue
