### ISSUE TITLE
Windows Border Theme in X-Gnome metacity-1 appearance wrong in Moden mode.

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/mint-19.1-beta#33]
**Describe the bug**
Switching between moden and traditional mode the Windows border theme changes.  Specifically the red highlight on the close button

**To Reproduce**
install AKTeal theme and switch between modes.

**Expected behavior**
The "X" close icon should always be red highlighted.

**Frequency**
Does the issue happen:
- [X] Always

**Edition (Desktop environment):**
In which edition is this happening?
- [X] Cinnamon Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [X] Post-install
- [X] Live session

**Screenshots**
1 screenshot in each mode and theme

**Locale:**
EN-US UTF8

**Additional context**
This IS a custom theme, however it was simply a download of another theme a a simple #FF0000 color change etc to the variables.
![screenshot from 2018-12-08 14-00-34](https://user-images.githubusercontent.com/26556059/49687523-14922b80-fad2-11e8-83f9-42bc8d2fdeef.png)
![screenshot from 2018-12-08 14-00-34](https://user-images.githubusercontent.com/26556059/49687526-1fe55700-fad2-11e8-8b8e-38bb50c4f5f6.png)

[AKteal.zip](https://github.com/linuxmint/mint-19.1-beta/files/2659803/AKteal.zip)

**Comment by smurphos** [comment]
Your theme includes these color constant definitions

`<constant name="C_button_close_bg_focused" value="gtk:custom(selected_bg_color,#FF0000)" />
<constant name="C_button_close_bg_hover" value="shade/gtk:custom(selected_bg_color,#000000)/1.14" />
<constant name="C_button_close_bg_active" value="shade/gtk:custom(selected_bg_color,#00FFFF)/0.8" />`

It is using the color from the active GTK3 theme if defined in the GTK3 theme by design. Mint-Y (Modern) provides a selected_bg_color, Mint-X (traditional) doesn't so the hardcoded defaults are used instead.

You need to fix your window-border theme  ;-)

**Comment by ChooChooAl** [comment]
I'm not sure I follow you, mostly since I'm good at changing #393939 to #FF0000 but that's about the extent of my XML knowledge or close to it.
Is there a way to fix this so it would work both ways?

**Comment by smurphos** [comment]
Change the lines I listed above in your theme to

`<constant name="C_button_close_bg_focused" value="#FF0000" />
<constant name="C_button_close_bg_hover" value="shade/#000000/1.14" />
<constant name="C_button_close_bg_active" value="shade/#00FFFF/0.8" />`

**Comment by ChooChooAl** [comment]
Thanks.
