### ISSUE TITLE
Nemo ignores [icon-view] thumbnail-size=48

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint-19.1-beta#40]
**Describe the bug**
Nemo seems to ignore the dconf value for:
[org/nemo/icon-view]
thumbnail-size=48

The default is 64.  When it is changed to 48 and ignore-view-metadata=true there is no effect.

**To Reproduce**
1. Go to 'dconf editor'
2. Click on '/org/nemo/icon-view/thumbnail-size'
3. Change the Default Thumbnail Icon Size from 64 to 48.
4. Go to /org/nemo/preferences/ignore-vew-metadata
5. Change to default to ignore "ignore-view-metadata=true"
6. Start Nemo.
7. Icons are still at 64 px.

**Expected behavior**
With changed values, expected Nemo to display icons at 48 px.

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [x] Live session

**Screenshots**
N/A.

**Locale:**
LANG=en_US.UTF-8
LANGUAGE=en_US

**Drivers:**
N/A.

**Additional context**
Is there an issue here or something being missed to make this happen?

**Comment by mtwebster** [comment]
The 'thumbnail-size' value is used only as a baseline for size calculations internally, it doesn't affect sizes in the view.

There was a bug I just fixed in the icon view, which ended up causing the initial view to use the metadata's zoom level rather than the 'default zoom level' when ignore-metadata was set.  This should work as expected now.  All of these settings can be changed in nemo's preferences btw (ignore metadata is in the Behavior tab)
