### ISSUE TITLE
Mint-Y-Dark have some icons with low contrast in buttons

### ISSUE THREAD

**Issue by otavioschwanck** [linuxmint/mint-19.1-beta#67]
**Describe the bug**
Some icons dont contrast well.

**To Reproduce**
1. Enable icons on buttons

**Expected behavior**
More white symbolic icons in dark theme.

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [x] Live session

**Screenshots**
Chrome dialog:
![image](https://user-images.githubusercontent.com/9551316/49895253-214ab280-fe37-11e8-9d90-61473fbee6f4.png)
![image](https://user-images.githubusercontent.com/9551316/49895338-52c37e00-fe37-11e8-9600-6b373cf31ceb.png)
Gnome Terminal close icon:
![image](https://user-images.githubusercontent.com/9551316/49895374-65d64e00-fe37-11e8-9543-c88b407f8a73.png)
Transmissions icons:
![image](https://user-images.githubusercontent.com/9551316/49895438-8f8f7500-fe37-11e8-8979-cda06f5ad36e.png)
Gimp:
![image](https://user-images.githubusercontent.com/9551316/49907553-c7a9ae80-fe5d-11e8-855b-537b1e84a49b.png)
Application Editor:
![image](https://user-images.githubusercontent.com/9551316/49907582-e7d96d80-fe5d-11e8-9d53-6c7acd61de6c.png)

Clicking on window title, the symbolic icons are dark:
![image](https://user-images.githubusercontent.com/9551316/49907711-8cf44600-fe5e-11e8-9e5e-be6e49fbd31b.png)

Xed plugins:
![image](https://user-images.githubusercontent.com/9551316/49895319-45a68f00-fe37-11e8-9279-5bd10de68bf5.png)

**Comment by clefebvre** [comment]
I fully agree with this, though I need to close it because it's a long term effort, not something that will be fixed this release.

These aren't symbolic icons, and that's the problem. They're fullcolor icons and there's no other way to make fullcolor work with dark and bright themes than to make them colorful, and that's hard to do, or it looks ugly.

What the icon theme is doing at the moment is to use some kind of grey which is visible both on dark and on light, it's a compromise. Ideally we should have -dark icon themes (but we're starting to have quite many already), or move to symbolic icons everywhere (and we do, a lot, but we can't force upstream to do the same).
