### ISSUE TITLE
Flatpak have adwaita theme instead Mint-y.

### ISSUE THREAD

**Issue by otavioschwanck** [linuxmint/mint-19.1-beta#69]
**Describe the bug**

**To Reproduce**
1. Install a flatpak (gcolorpicker, telegram) with the default software manager.
2. Open it

**Expected behavior**
Mint-y theme.

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [ ] Live session

**Screenshots**
![image](https://user-images.githubusercontent.com/9551316/49906404-db9ee180-fe58-11e8-8149-2df0074e6772.png)

**Locale:**
pt_BR

**Comment by mtwebster** [comment]
Possibly you don't have Mint-Y, you have some color variant active instead?

Only Mint-Y and Mint-Y-Darker are currently on flathub.  If you set your active theme to one of those, they install fine with the programs you mentioned (In fact, telegram installs both themes because they're visible to your 'normal' theme system).

Unfortunately, however, if you have one of the color variants active, flatpak apps will still fall back to Adwaita theme.

I don't think there's a lot we can do here for now, except work towards packaging the remainder of our themes for flatpak.

Can you tell me if you have this issue with either Mint-Y or Mint-Y-Darker active? Or is it just with color variants?

**Comment by otavioschwanck** [comment]
> Possibly you don't have Mint-Y, you have some color variant active instead?
> 
> Only Mint-Y and Mint-Y-Darker are currently on flathub. If you set your active theme to one of those, they install fine with the programs you mentioned (In fact, telegram installs both themes because they're visible to your 'normal' theme system).
> 
> Unfortunately, however, if you have one of the color variants active, flatpak apps will still fall back to Adwaita theme.
> 
> I don't think there's a lot we can do here for now, except work towards packaging the remainder of our themes for flatpak.
> 
> Can you tell me if you have this issue with either Mint-Y or Mint-Y-Darker active? Or is it just with color variants?

With mint-y-dark works well!

Just need to add the other variants to flatpak then.  

![image](https://user-images.githubusercontent.com/9551316/50012278-5d038a80-ffa5-11e8-8f6c-1fb738f32119.png)

**Comment by clefebvre** [comment]
Will do, adding to roadmap.
